# Generated by Django 4.2.6 on 2023-10-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clavicle', '0002_auto_20231008_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentialanalysis',
            name='fold_change_col',
            field=models.TextField(blank=True, null=True),
        ),
    ]
