# Generated by Django 4.2.6 on 2023-10-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clavicle', '0003_differentialanalysis_fold_change_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentialanalysis',
            name='file_type',
            field=models.CharField(choices=[('csv', 'csv'), ('tsv', 'tsv'), ('txt', 'tabulated text'), ('txt', 'space separated text')], default='tsv', max_length=3),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='file_type',
            field=models.CharField(choices=[('csv', 'csv'), ('tsv', 'tsv'), ('txt', 'tabulated text'), ('txt', 'space separated text')], default='tsv', max_length=3),
        ),
    ]
