# Generated by Django 4.2.6 on 2023-10-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clavicle', '0004_differentialanalysis_file_type_rawdata_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='differentialanalysis',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
