# Generated by Django 4.2.6 on 2023-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clavicle', '0005_alter_differentialanalysis_data_alter_rawdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
