# Generated by Django 4.2.6 on 2023-10-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clavicle', '0006_rawdata_value_alter_rawdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='sample_cols',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
